In [1]:
import pandas as pd

In [2]:
df =pd.read_csv("IMDB Dataset.csv")

In [3]:
import re

In [4]:
def removal_html_tag(text):
    pattern =re.compile('<.*?>')
    return pattern.sub(r'',text)

In [5]:
text = '<p>This is the second paragraph, separated by a line.</p>'

print(removal_html_tag(text))

This is the second paragraph, separated by a line.

In [6]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
df['review']=df['review'].apply(removal_html_tag)

In [8]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [9]:
import string
# translator = str.maketrans('', '', string.punctuation)
marks = string.punctuation

In [10]:
marks

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [11]:
def remove_punc(text):
    for char in marks:
        text= text.replace(char,'')
    return text

In [12]:
df['review']=df['review'].apply(remove_punc)

In [13]:
def remove_punc1(text):
    return text.translate(str.maketrans('','',marks))

In [14]:
df['review']=df['review'].apply(remove_punc1)

In [15]:
df['review']

0        One of the other reviewers has mentioned that ...
1        A wonderful little production The filming tech...
2        I thought this was a wonderful way to spend ti...
3        Basically theres a family where a little boy J...
4        Petter Matteis Love in the Time of Money is a ...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot bad dialogue bad acting idiotic direc...
49997    I am a Catholic taught in parochial elementary...
49998    Im going to have to disagree with the previous...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: str

In [16]:
!pip install autocorrect

Defaulting to user installation because normal site-packages is not writeable
Collecting autocorrect
  Downloading autocorrect-2.6.1.tar.gz (622 kB)
     ---------------------------------------- 0.0/622.8 kB ? eta -:--:--
     ---------------------------------------- 622.8/622.8 kB 5.9 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: autocorrect
  Building wheel for autocorrect (pyproject.toml): started
  Building wheel for autocorrect (pyproject.toml): finished with status 'done'
  Created wheel for autocorrect: filename=autocorrect-2.6.1-py3-none-any.whl size=622440 sha256=7842bcc17250251271ee777ec4cdf5befa761d27b7c2550f508f22715c52a711
  Stored in directory: c:\users\subha\appdata\local\pip\cache\wheels\a1\26\ab\db677b2fc998f5be196cf69dad539efa43303ccf0c77453f20
Successfully built autocorrect
Installing collected packages: autocorrect
Successfully installed autocorrect-2.6.1

In [18]:
!pip install spellchecker

Defaulting to user installation because normal site-packages is not writeable
Collecting spellchecker
  Downloading spellchecker-0.4.tar.gz (3.9 MB)
     ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
     ---------- ----------------------------- 1.0/3.9 MB 11.0 MB/s eta 0:00:01
     ------------------------------------- -- 3.7/3.9 MB 12.6 MB/s eta 0:00:01
     ---------------------------------------- 3.9/3.9 MB 12.2 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: setuptools in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from spellchecker) (84.0.0)
Collecting inexactsearch (from spellchecker)
  Downloading inexactsearch-1.0.2.tar.gz (21 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting soundex>=1.0 (from inexactsearch->spellchecker)
  Downloading soundex-1.1.3.tar.gz (9.1 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting silpa_common>=0.3 (from inexactsearch->spellchecker)
  Downloading silpa_common-0.3.tar.gz (9.4 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: spellchecker, inexactsearch, silpa_common, soundex
  Building wheel for spellchecker (pyproject.toml): started
  Building wheel for spellchecker (pyproject.toml): finished with status 'done'
  Created wheel for spellchecker: filename=spellchecker-0.4-py3-none-any.whl size=3924879 sha256=04e7d7a384cc0f6238bf38d1236ab680d15faa19acbb7a77c46e00ec68f2c0da
  Stored in directory: c:\users\subha\appdata\local\pip\cache\wheels\30\39\c2\ad2a37fafd7cbd18d26a5ebc5e9f0842d06cbf9a819e6b97b6
  Building wheel for inexactsearch (pyproject.toml): started
  Building wheel for inexactsearch (pyproject.toml): finished with status 'done'
  Created wheel for inexactsearch: filename=inexactsearch-1.0.2-py3-none-any.whl size=7212 sha256=58ab77ff631f6209b9e35bc5b90316d968622feade6f7f167963ab49cbb05763
  Stored in directory: c:\users\subha\appdata\local\pip\cache\wheels\4d\8e\4a\398c7b86d59ec2bd1ff4497d9cabaf1b62d08492ac8740bf4f
  Building wheel for silpa_common (pyproject.toml): started
  Building wheel for silpa_common (pyproject.toml): finished with status 'done'
  Created wheel for silpa_common: filename=silpa_common-0.3-py3-none-any.whl size=8594 sha256=0c173fe8c4893a07d240f095b62f10a6deb1dfcd25273bff097039244ec41e93
  Stored in directory: c:\users\subha\appdata\local\pip\cache\wheels\75\ef\16\5ecf38a06c1a9d3203b89b5d2d69f09ffc6cbae796124e0943
  Building wheel for soundex (pyproject.toml): started
  Building wheel for soundex (pyproject.toml): finished with status 'done'
  Created wheel for soundex: filename=soundex-1.1.3-py3-none-any.whl size=8964 sha256=5cd3b588732baa16dd7aaec35da9221d287cc8b8a3f4e6500d8fc57252568b94
  Stored in directory: c:\users\subha\appdata\local\pip\cache\wheels\f3\8d\81\67f03367aa5566702d7045683e327d07e59e3af39f73d40cbd
Successfully built spellchecker inexactsearch silpa_common soundex
Installing collected packages: silpa_common, soundex, inexactsearch, spellchecker

   ------------------------------ --------- 3/4 [spellchecker]
   ------------------------------ --------- 3/4 [spellchecker]
   ---------------------------------------- 4/4 [spellchecker]

Successfully installed inexactsearch-1.0.2 silpa_common-0.3 soundex-1.1.3 spellchecker-0.4