In [1]:
import pandas as pd

In [2]:
df =pd.read_csv("IMDB Dataset.csv")

In [3]:
import re

In [4]:
def removal_html_tag(text):
    pattern =re.compile('<.*?>')
    return pattern.sub(r'',text)

In [5]:
text = '<p>This is the second paragraph, separated by a line.</p>'

print(removal_html_tag(text))

This is the second paragraph, separated by a line.

In [6]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
df['review']=df['review'].apply(removal_html_tag)

In [8]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [9]:
import string
# translator = str.maketrans('', '', string.punctuation)
marks = string.punctuation

In [10]:
marks

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [11]:
def remove_punc(text):
    for char in marks:
        text= text.replace(char,'')
    return text

In [12]:
df['review']=df['review'].apply(remove_punc)

In [13]:
def remove_punc1(text):
    return text.translate(str.maketrans('','',marks))

In [14]:
df['review']=df['review'].apply(remove_punc1)

In [15]:
df['review']

0        One of the other reviewers has mentioned that ...
1        A wonderful little production The filming tech...
2        I thought this was a wonderful way to spend ti...
3        Basically theres a family where a little boy J...
4        Petter Matteis Love in the Time of Money is a ...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot bad dialogue bad acting idiotic direc...
49997    I am a Catholic taught in parochial elementary...
49998    Im going to have to disagree with the previous...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: str

In [16]:
!pip install autocorrect

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: autocorrect in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (2.6.1)

In [17]:
!pip install spellchecker

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: spellchecker in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (0.4)
Requirement already satisfied: setuptools in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from spellchecker) (84.0.0)
Requirement already satisfied: inexactsearch in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from spellchecker) (1.0.2)
Requirement already satisfied: soundex>=1.0 in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from inexactsearch->spellchecker) (1.1.3)
Requirement already satisfied: silpa_common>=0.3 in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from inexactsearch->spellchecker) (0.3)

In [18]:
!pip install  textblob

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: textblob in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (0.20.1)
Requirement already satisfied: nltk>=3.9 in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from textblob) (3.10.3)
Requirement already satisfied: defusedxml in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from nltk>=3.9->textblob) (0.7.1)
Requirement already satisfied: click in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from nltk>=3.9->textblob) (8.5.0)
Requirement already satisfied: joblib in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from nltk>=3.9->textblob) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from nltk>=3.9->textblob) (2026.9.10)
Requirement already satisfied: tqdm in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from nltk>=3.9->textblob) (4.70.1)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from joblib->nltk>=3.9->textblob) (3.1.2)
Requirement already satisfied: colorama in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from tqdm->nltk>=3.9->textblob) (0.4.6)

In [19]:
from textblob import TextBlob

In [20]:
incorrect_text= "Yesterday, the goverment official recieved an urgent mesage from his collaege regarding the accomodation for the upcoming symposium, but teh system ws unable to process the requst due to a technical glich."

TextBlb = TextBlob(incorrect_text)
corrected_text=TextBlb.correct().string
print(TextBlb)
print(corrected_text)

Yesterday, the goverment official recieved an urgent mesage from his collaege regarding the accomodation for the upcoming symposium, but teh system ws unable to process the requst due to a technical glich.
Yesterday, the government official received an urgent message from his college regarding the accommodation for the coming symposium, but the system was unable to process the request due to a technical which.

In [21]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production The filming tech...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically theres a family where a little boy J...  negative
4      Petter Matteis Love in the Time of Money is a ...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot bad dialogue bad acting idiotic direc...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  Im going to have to disagree with the previous...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [24]:
import nltk

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\subha\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [26]:
from nltk.corpus import stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [28]:
text ='I am going to the market because I need to buy some vegetables and fruits.'

def remove_stopwords(text):
    new_text =[]
    for words in text.split():
        if words in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(words)
    x= new_text[:]
    new_text.clear()
    return " ".join(x)

remove_stopwords(text)

'I  going   market  I need  buy  vegetables  fruits.'

In [29]:
!pip install demoji

Defaulting to user installation because normal site-packages is not writeable
Collecting demoji
  Downloading demoji-2.0.0-py3-none-any.whl.metadata (5.9 kB)
Downloading demoji-2.0.0-py3-none-any.whl (43 kB)
Installing collected packages: demoji
Successfully installed demoji-2.0.0

In [30]:
!pip install emoji

Defaulting to user installation because normal site-packages is not writeable
Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ---------------------------------------- 0.0/608.4 kB ? eta -:--:--
   ---------------------------------------- 608.4/608.4 kB 4.4 MB/s  0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [31]:
import emoji

text = "Good morning! ☀️ Have a nice day! 🌸😊"

# Replace emojis with an empty string
cleaned_text = emoji.replace_emoji(text, replace='')

print(cleaned_text)
# Output: Good morning!  Have a nice day!

Good morning!  Have a nice day!

In [32]:
import demoji

text = "Python is fun! 🐍🔥 Let's code! 💻🎉"

# Replace all emojis with an empty string
cleaned_text = demoji.replace(text, "")

print(cleaned_text)
# Output: Python is fun!  Let's code!

Python is fun!  Let's code!